updated workflows for beta process

diff --git a/.github/workflows/beta-promote.yaml b/.github/workflows/beta-promote.yaml
--- a/.github/workflows/beta-promote.yaml
+++ b/.github/workflows/beta-promote.yaml
@@ -4,6 +4,11 @@ on:
     # Every wednesdays, at 2h30/3h30 am(EST/EDT)
     # running after the beta-auto-merge workflow to avoid overlap
     - cron: "30 7 * * WED"
+  pull_request:
+    types:
+      - 'opened'
+      - 'synchronize'
+      - 'reopened'
 
 jobs:
   get-bi-weekly-schedule:
@@ -22,37 +27,42 @@ jobs:
           echo "This is week #$numWeek, biweekly modulo is at $((numWeek % 2))."
           echo "Job will run on value==0"
 
-  promote-beta-to-prod:
+  create-pr-beta-to-prod:
     runs-on: ubuntu-latest
     needs: get-bi-weekly-schedule
-    if: ${{ needs.get-bi-weekly-schedule.outputs.biweekly == 0 }}
+    # if: ${{ needs.get-bi-weekly-schedule.outputs.biweekly == 0 }}
     env:
       GH_TOKEN: ${{ github.token }}
     steps:    
-    - name: "Checkout master"
+    - name: "Checkout beta"
       uses: actions/checkout@v4
       with:
-        fetch-depth: 0
-        ref: master
+        # fetch-depth: 0
+        ref: beta
     
+    - name: Create PR for beta to master
+      run: |
+        gh pr create --base master --title "chore: Promote beta to master" \
+          --body "Automatically generated PR to merge beta to master"
     # required step for the merge command to work
-    - name: Set Git config
-      run: |
-        git config --local user.email "actions@github.com"
-        git config --local user.name "GitHub Actions"
+    # - name: Set Git config
+    #   run: |
+    #     git config --local user.email "actions@github.com"
+    #     git config --local user.name "GitHub Actions"
     
-    - name: "Merge Beta to Master"
-      run: git merge origin/beta --verbose --ff --no-edit
+    # - name: "Merge Beta to Master"
+    #   run: git merge origin/beta --verbose --ff --no-edit
 
-    - name: "Push updated master to remote"
-      run: |
-        if [[ -z "$(git status --porcelain)" ]]; then
-          echo "Clean working tree. Pushing to master"
-          git push
-        else
-          echo "Dirty working tree. Not pushing to master"
-          git status
+    # - name: "Push updated master to remote"
+    #   run: |
+    #     if [[ -z "$(git status --porcelain)" ]]; then
+    #       echo "Clean working tree. Pushing to master"
+    #       git push
+    #     else
+    #       echo "Dirty working tree. Not pushing to master"
+    #       git status
 
-          # fail the job
-          exit 1
-        fi
+    #       # fail the job
+    #       exit 1
+    #     fi
+
